In [12]:
import tensorflow as tf
import numpy as np

In [11]:
a = tf.constant(np.array([1,2,3]), dtype=tf.float32)
b = tf.constant(np.array([4,5,6]), dtype=tf.float32)
c = tf.tensordot(a, b, 1)
c.numpy()

np.float32(32.0)

In [14]:
d = tf.add(a, b)
e = tf.multiply(a, b)
f = tf.subtract(a, b)
print(d.numpy())
print(e.numpy())
print(f.numpy())

[5. 7. 9.]
[ 4. 10. 18.]
[-3. -3. -3.]
