In [2]:
import torch
import torch.nn as nn

In [3]:
class LR(nn.Module):
    def __init__(self, input_dim, output_dim):
        super(LR, self).__init__()
        self.linear = nn.Linear(input_dim, output_dim)

    def forward(self, x):
        return self.linear(x)

In [6]:
model = LR(1, 1)
model.state_dict()['linear.weight'].data[0] = torch.tensor([0.5])
model.state_dict()['linear.bias'].data[0] = torch.tensor([3.0])
print(list(model.parameters()))

[Parameter containing:
tensor([[0.5000]], requires_grad=True), Parameter containing:
tensor([3.], requires_grad=True)]


In [7]:
x = torch.tensor([[1.0]])
y = model(x)
print(y)

tensor([[3.5000]], grad_fn=<AddmmBackward0>)


In [8]:
x = torch.tensor([[1.0], [2.0], [3.0]])
y = model(x)
print(y)

tensor([[3.5000],
        [4.0000],
        [4.5000]], grad_fn=<AddmmBackward0>)
