In [8]:
import torch
import torch.nn as nn

In [22]:
torch.manual_seed(1) # For reproducibility
# Create a Linear layer: 3 inputs -> 2 outputs
layer = nn.Linear(3, 2)
# Create a random input tensor with 3 features
input_tensor = torch.randn(1, 3)
print("Input tensor:", input_tensor)
# Apply the linear layer to the input tensor
output_tensor = layer(input_tensor)
# Print the output tensor
print("Output tensor:", output_tensor)
# Parameters shapes
print("Weights shape:", layer.weight.shape)
print("Biases shape:", layer.bias.shape)
# Parameters values
print("Weights:", layer.weight)
print("Biases:", layer.bias)
print("params", list(layer.parameters()))


Input tensor: tensor([[-0.4519, -0.1661, -1.5228]])
Output tensor: tensor([[-0.0404, -0.2657]], grad_fn=<AddmmBackward0>)
Weights shape: torch.Size([2, 3])
Biases shape: torch.Size([2])
Weights: Parameter containing:
tensor([[ 0.2975, -0.2548, -0.1119],
        [ 0.2710, -0.5435,  0.3462]], requires_grad=True)
Biases: Parameter containing:
tensor([-0.1188,  0.2937], requires_grad=True)
params [Parameter containing:
tensor([[ 0.2975, -0.2548, -0.1119],
        [ 0.2710, -0.5435,  0.3462]], requires_grad=True), Parameter containing:
tensor([-0.1188,  0.2937], requires_grad=True)]
